CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOL_ROOTS := ImemInscount ImemROIThreads ImemROIThreadsRange

include $(CONFIG_ROOT)/makefile.config
include $(TOOLS_ROOT)/Config/makefile.default.rules
